export const seedAssets = [
  {
    id: "A1245580",
    name: "Metal Pallet Shelf",
    category: "Storage",
    location: "Warehouse A",
    quantity: 12,
    condition: "Good",
    status: "Available",
    cost: 1275,
    barcodeType: "Internal barcode",
    barcode: "SHELF-A-001",
  },
  {
    id: "A1245582",
    name: "Cargo Trolley",
    category: "Equipment",
    location: "Dispatch",
    quantity: 4,
    condition: "Excellent",
    status: "Available",
    cost: 125,
    barcodeType: "UPC",
    barcode: "012345678905",
  },
  {
    id: "A1245584",
    name: "Orange Crate",
    category: "Storage",
    location: "Warehouse B",
    quantity: 36,
    condition: "Good",
    status: "Available",
    cost: 40,
    barcodeType: "Internal barcode",
    barcode: "CRATE-ORANGE-01",
  },
  {
    id: "A1245585",
    name: "Blue Storage Bins",
    category: "Storage",
    location: "Warehouse A",
    quantity: 18,
    condition: "Fair",
    status: "Low stock",
    cost: 28,
    barcodeType: "EAN",
    barcode: "5901234123457",
  },
];
